source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'JVTouchEventsWindow' do
  pod "JVTouchEventsWindow", :path => "../"
end

target 'Tests' do
  pod "JVTouchEventsWindow", :path => "../"
end
