source 'https://github.com/CocoaPods/Specs.git'

target 'JVTouchEventsWindow', :exclusive => true do
  pod "JVTouchEventsWindow", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "JVTouchEventsWindow", :path => "../"

  
end
